_format_version: "2.1"

services:
  - name: auth-v1-open
    url: http://supabase-auth:9999/verify
    routes:
      - name: auth-v1-open
        strip_path: true
        paths:
          - /auth/v1/verify
    plugins:
      - name: cors
        config:
          origins:
            - http://localhost:8082
            - http://localhost:19006
            - http://localhost:19000
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Language
            - Content-Language
            - Content-Type
            - Authorization
            - apikey
            - X-Client-Name
            - X-Client-Version
            - X-Canadian-Compliance
          exposed_headers:
            - X-Total-Count
            - X-RateLimit-Limit
            - X-RateLimit-Remaining
          credentials: true
          max_age: 3600

  - name: auth-v1-open-callback
    url: http://supabase-auth:9999/callback
    routes:
      - name: auth-v1-open-callback
        strip_path: true
        paths:
          - /auth/v1/callback
    plugins:
      - name: cors
        config:
          origins:
            - http://localhost:8082
            - http://localhost:19006
            - http://localhost:19000
          credentials: true

  - name: auth-v1
    url: http://supabase-auth:9999/
    routes:
      - name: auth-v1-all
        strip_path: true
        paths:
          - /auth/v1/
    plugins:
      - name: cors
        config:
          origins:
            - http://localhost:8082
            - http://localhost:19006
            - http://localhost:19000
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Language
            - Content-Language
            - Content-Type
            - Authorization
            - apikey
            - X-Client-Name
            - X-Client-Version
            - X-Canadian-Compliance
          credentials: true

  - name: rest-v1
    url: http://supabase-rest:3000/
    routes:
      - name: rest-v1-all
        strip_path: true
        paths:
          - /rest/v1/
    plugins:
      - name: cors
        config:
          origins:
            - http://localhost:8082
            - http://localhost:19006
            - http://localhost:19000
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Language
            - Content-Language
            - Content-Type
            - Authorization
            - apikey
            - Prefer
            - Range
            - X-Client-Name
            - X-Client-Version
            - X-Canadian-Compliance
          credentials: true

  - name: storage-v1
    url: http://supabase-storage:5000/
    routes:
      - name: storage-v1-all
        strip_path: true
        paths:
          - /storage/v1/
    plugins:
      - name: cors
        config:
          origins:
            - http://localhost:8082
            - http://localhost:19006
            - http://localhost:19000
          credentials: true

  - name: meta
    url: http://supabase-meta:8080/
    routes:
      - name: meta-all
        strip_path: true
        paths:
          - /pg/
    plugins:
      - name: cors
        config:
          origins:
            - http://localhost:8082
            - http://localhost:19006
            - http://localhost:19000
          credentials: true

consumers: []
plugins: []